// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// EncryptedSecretListerExpansion allows custom methods to be added to
// EncryptedSecretLister.
type EncryptedSecretListerExpansion interface{}

// EncryptedSecretNamespaceListerExpansion allows custom methods to be added to
// EncryptedSecretNamespaceLister.
type EncryptedSecretNamespaceListerExpansion interface{}
