/*
Copyright 2018 The Kuncen Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	kuncen_v1alpha1 "github.com/fajran/kuncen/pkg/apis/kuncen/v1alpha1"
	versioned "github.com/fajran/kuncen/pkg/client/clientset/versioned"
	internalinterfaces "github.com/fajran/kuncen/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/fajran/kuncen/pkg/client/listers/kuncen/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// EncryptedSecretInformer provides access to a shared informer and lister for
// EncryptedSecrets.
type EncryptedSecretInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.EncryptedSecretLister
}

type encryptedSecretInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewEncryptedSecretInformer constructs a new informer for EncryptedSecret type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewEncryptedSecretInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredEncryptedSecretInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredEncryptedSecretInformer constructs a new informer for EncryptedSecret type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredEncryptedSecretInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KuncenV1alpha1().EncryptedSecrets(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KuncenV1alpha1().EncryptedSecrets(namespace).Watch(options)
			},
		},
		&kuncen_v1alpha1.EncryptedSecret{},
		resyncPeriod,
		indexers,
	)
}

func (f *encryptedSecretInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredEncryptedSecretInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *encryptedSecretInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&kuncen_v1alpha1.EncryptedSecret{}, f.defaultInformer)
}

func (f *encryptedSecretInformer) Lister() v1alpha1.EncryptedSecretLister {
	return v1alpha1.NewEncryptedSecretLister(f.Informer().GetIndexer())
}
